# Generated by Django 3.2.16 on 2022-12-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221214_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='tag',
            new_name='tags',
        ),
    ]
