# Generated by Django 3.2.16 on 2022-12-21 05:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221215_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.step_image_file_path),
        ),
    ]
